spring.application.name=config-server-main

server.port=8888

# Git repo URL (\uD83D\uDD25 important)
spring.cloud.config.server.git.uri=https://github.com/Nilanjeet18/config-repo

# Optional: clone automatically
spring.cloud.config.server.git.clone-on-start=true

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/